import sqlite3
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

db = sqlite3.connect("STC_DB.db")
cursor = db.cursor()

try:
    
    cursor.execute("CREATE TABLE USER(password varchar(15))")
    print("user table create sucessfull!")
    db.commit()

except:
    print("User Table already added!")



try:
    cursor.execute("""CREATE TABLE teacher(first_name varchar(20),
                                                full_name varchar(50),
                                                NIC_NO varchar(12),
                                                Date_Of_Birth varchar(20),
                                                Addmision_date varchar(20),
                                                Address varchar(50),
                                                Contacts int(26),
                                                email varchar(40))""")
    print("teachers table create sucessfull!")
        
    db.commit()
except:
    print("teacher table already added!")



try:    
    cursor.execute("""CREATE TABLE STUDENTS(    full_name varchar(50),
                                                NIC_NO varchar(12),
                                                Date_of_birth varchar(20),
                                                Addmission_no int(6),
                                                Addmited_date varchar(20),
                                                Address varchar(40),
                                                Contacts int(30),
                                                p_name varchar(50))""")
    print("students table create sucessfull!!")
    db.commit()

except:
    print("student table already added!")
db.close()

class Ui_Form(object):
    def savet(self):
        db = sqlite3.connect("STC_DB.db")
        cursor = db.cursor()
        a = self.lineEdit.text()
        b = self.lineEdit_13.text()
        c = self.lineEdit_16.text()
        d = self.dateEdit_5.text()
        e = self.dateEdit_6.text()
        f = self.lineEdit_17.text()
        g = self.lineEdit_18.text()
        h = self.lineEdit_19.text()
        try:
            sql = ("""INSERT INTO teacher(first_name,
                                                  full_name,
                                                  NIC_NO,
                                                  Date_Of_Birth,
                                                  Addmision_date,
                                                  Address,
                                                  Contacts,
                                                  email)values("%s","%s","%s","%s","%s","%s","%s","%s")"""%(a,b,c,d,e,f,g,h))
            results = cursor.execute("select*from teacher")
        
            data = results.fetchall()
        
            for row in data:
                d1 = row[0]
                d2 = row[2]
            if d1==a or d2==c:
                print("This name or NIC_No already added!try another member..")
            elif d1!=a or d2!=c:
                cursor.execute(sql)
                print("data saved sucessfully!")
                db.commit()
        except:
            print("Something went wrong!!")
        db.close()

    def savest(self):
        db = sqlite3.connect("STC_DB.db")
        cursor = db.cursor()
        
        i = self.fname.text()
        j = self.lineEdit_3.text()
        k = self.dateEdit_2.text()
        l = self.lineEdit_4.text()
        m = self.dateEdit.text()
        n = self.lineEdit_6.text()
        o = self.lineEdit_7.text()
        p = self.lineEdit_8.text()

        print(i,j,k,l,m,n,o,p)
        
        try:
            sql = ("""INSERT INTO STUDENTS(full_name,
                                            NIC_NO,
                                            Date_of_birth,
                                            Addmission_no,
                                            Addmited_date,
                                            Address,
                                            Contacts,
                                            p_name)values("%s","%s","%s","%s","%s","%s","%s","%s") """%(i,j,k,l,m,n,o,p))
                            
            results = cursor.execute("select*from STUDENTS")
            
            data = results.fetchall()
            
            for row in data:
                d1 = row[4]
                
            if d1==l:
                print("This name or NIC_No already added!try another member..")
            else:
                cursor.execute(sql)
                print("data saved sucessfully!")
                db.commit()
        except:
            print("Something went wrong!!")
        db.close()
    
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1044, 671)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(0, 50))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Old English Text MT"))
        font.setPointSize(36)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label = QtGui.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(120, 120))
        self.label.setMaximumSize(QtCore.QSize(120, 120))
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setStyleSheet(_fromUtf8("image: url(:/newPrefix/stc.png);"))
        self.label.setText(_fromUtf8(""))
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.label_42 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_42.setFont(font)
        self.label_42.setText(_fromUtf8(""))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout.addWidget(self.label_42, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget_3 = QtGui.QTabWidget(self.tab)
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.lineEdit_17 = QtGui.QLineEdit(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_17.setFont(font)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.gridLayout_8.addWidget(self.lineEdit_17, 5, 3, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_8.addWidget(self.lineEdit, 0, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_8.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_8.addWidget(self.label_19, 1, 0, 1, 1)
        self.dateEdit_5 = QtGui.QDateEdit(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit_5.setFont(font)
        self.dateEdit_5.setObjectName(_fromUtf8("dateEdit_5"))
        self.gridLayout_8.addWidget(self.dateEdit_5, 3, 3, 1, 1)
        self.lineEdit_13 = QtGui.QLineEdit(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.gridLayout_8.addWidget(self.lineEdit_13, 1, 3, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_8.addWidget(self.label_25, 5, 0, 1, 1)
        self.lineEdit_18 = QtGui.QLineEdit(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_18.setFont(font)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.gridLayout_8.addWidget(self.lineEdit_18, 6, 3, 1, 1)
        self.line_19 = QtGui.QFrame(self.tab_5)
        self.line_19.setFrameShape(QtGui.QFrame.VLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.gridLayout_8.addWidget(self.line_19, 2, 1, 1, 1)
        self.lineEdit_16 = QtGui.QLineEdit(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.gridLayout_8.addWidget(self.lineEdit_16, 2, 3, 1, 1)
        self.label_26 = QtGui.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_8.addWidget(self.label_26, 6, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_8.addWidget(self.label_23, 3, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_8.addWidget(self.label_22, 2, 0, 1, 1)
        self.line = QtGui.QFrame(self.tab_5)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_8.addWidget(self.line, 0, 1, 1, 1)
        self.line_20 = QtGui.QFrame(self.tab_5)
        self.line_20.setFrameShape(QtGui.QFrame.VLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.gridLayout_8.addWidget(self.line_20, 3, 1, 1, 1)
        self.dateEdit_6 = QtGui.QDateEdit(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit_6.setFont(font)
        self.dateEdit_6.setObjectName(_fromUtf8("dateEdit_6"))
        self.gridLayout_8.addWidget(self.dateEdit_6, 4, 3, 1, 1)
        self.line_11 = QtGui.QFrame(self.tab_5)
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.gridLayout_8.addWidget(self.line_11, 1, 1, 1, 1)
        self.line_21 = QtGui.QFrame(self.tab_5)
        self.line_21.setFrameShape(QtGui.QFrame.VLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName(_fromUtf8("line_21"))
        self.gridLayout_8.addWidget(self.line_21, 4, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_8.addWidget(self.label_24, 4, 0, 1, 1)
        self.line_23 = QtGui.QFrame(self.tab_5)
        self.line_23.setFrameShape(QtGui.QFrame.VLine)
        self.line_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_23.setObjectName(_fromUtf8("line_23"))
        self.gridLayout_8.addWidget(self.line_23, 6, 1, 1, 1)
        self.line_22 = QtGui.QFrame(self.tab_5)
        self.line_22.setFrameShape(QtGui.QFrame.VLine)
        self.line_22.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_22.setObjectName(_fromUtf8("line_22"))
        self.gridLayout_8.addWidget(self.line_22, 5, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButton_11 = QtGui.QPushButton(self.tab_5)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.horizontalLayout_4.addWidget(self.pushButton_11)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pushButton_5 = QtGui.QPushButton(self.tab_5)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon1)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_4.addWidget(self.pushButton_5)
        self.gridLayout_8.addLayout(self.horizontalLayout_4, 8, 3, 1, 1)
        self.label_27 = QtGui.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_8.addWidget(self.label_27, 7, 0, 1, 1)
        self.line_24 = QtGui.QFrame(self.tab_5)
        self.line_24.setFrameShape(QtGui.QFrame.VLine)
        self.line_24.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_24.setObjectName(_fromUtf8("line_24"))
        self.gridLayout_8.addWidget(self.line_24, 7, 1, 1, 1)
        self.lineEdit_19 = QtGui.QLineEdit(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_19.setFont(font)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.gridLayout_8.addWidget(self.lineEdit_19, 7, 3, 1, 1)
        self.tabWidget_3.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.teacher = QtGui.QTableWidget(self.tab_6)
        self.teacher.setObjectName(_fromUtf8("teacher"))
        self.teacher.setColumnCount(7)
        self.teacher.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.teacher.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.teacher.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.teacher.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.teacher.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.teacher.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.teacher.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.teacher.setHorizontalHeaderItem(6, item)
        self.gridLayout_9.addWidget(self.teacher, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_28 = QtGui.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_5.addWidget(self.label_28)
        self.lineEdit_20 = QtGui.QLineEdit(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_20.setFont(font)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.horizontalLayout_5.addWidget(self.lineEdit_20)
        self.pushButton_6 = QtGui.QPushButton(self.tab_6)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon2)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout_5.addWidget(self.pushButton_6)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.gridLayout_9.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lineEdit_22 = QtGui.QLineEdit(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_22.setFont(font)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.gridLayout_4.addWidget(self.lineEdit_22, 1, 2, 1, 1)
        self.lineEdit_24 = QtGui.QLineEdit(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_24.setFont(font)
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.gridLayout_4.addWidget(self.lineEdit_24, 5, 2, 1, 1)
        self.label_31 = QtGui.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_4.addWidget(self.label_31, 2, 0, 1, 1)
        self.line_30 = QtGui.QFrame(self.tab_7)
        self.line_30.setFrameShape(QtGui.QFrame.VLine)
        self.line_30.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_30.setObjectName(_fromUtf8("line_30"))
        self.gridLayout_4.addWidget(self.line_30, 5, 1, 1, 1)
        self.line_28 = QtGui.QFrame(self.tab_7)
        self.line_28.setFrameShape(QtGui.QFrame.VLine)
        self.line_28.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_28.setObjectName(_fromUtf8("line_28"))
        self.gridLayout_4.addWidget(self.line_28, 3, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_4.addWidget(self.label_33, 4, 0, 1, 1)
        self.dateEdit_7 = QtGui.QDateEdit(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit_7.setFont(font)
        self.dateEdit_7.setObjectName(_fromUtf8("dateEdit_7"))
        self.gridLayout_4.addWidget(self.dateEdit_7, 3, 2, 1, 1)
        self.label_30 = QtGui.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_4.addWidget(self.label_30, 1, 0, 1, 1)
        self.lineEdit_21 = QtGui.QLineEdit(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_21.setFont(font)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.gridLayout_4.addWidget(self.lineEdit_21, 0, 2, 1, 1)
        self.label_35 = QtGui.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_4.addWidget(self.label_35, 6, 0, 1, 1)
        self.line_29 = QtGui.QFrame(self.tab_7)
        self.line_29.setFrameShape(QtGui.QFrame.VLine)
        self.line_29.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_29.setObjectName(_fromUtf8("line_29"))
        self.gridLayout_4.addWidget(self.line_29, 4, 1, 1, 1)
        self.lineEdit_25 = QtGui.QLineEdit(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_25.setFont(font)
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.gridLayout_4.addWidget(self.lineEdit_25, 6, 2, 1, 1)
        self.dateEdit_8 = QtGui.QDateEdit(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit_8.setFont(font)
        self.dateEdit_8.setObjectName(_fromUtf8("dateEdit_8"))
        self.gridLayout_4.addWidget(self.dateEdit_8, 4, 2, 1, 1)
        self.label_29 = QtGui.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_4.addWidget(self.label_29, 0, 0, 1, 1)
        self.line_26 = QtGui.QFrame(self.tab_7)
        self.line_26.setFrameShape(QtGui.QFrame.VLine)
        self.line_26.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_26.setObjectName(_fromUtf8("line_26"))
        self.gridLayout_4.addWidget(self.line_26, 1, 1, 1, 1)
        self.line_27 = QtGui.QFrame(self.tab_7)
        self.line_27.setFrameShape(QtGui.QFrame.VLine)
        self.line_27.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_27.setObjectName(_fromUtf8("line_27"))
        self.gridLayout_4.addWidget(self.line_27, 2, 1, 1, 1)
        self.lineEdit_26 = QtGui.QLineEdit(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_26.setFont(font)
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.gridLayout_4.addWidget(self.lineEdit_26, 7, 2, 1, 1)
        self.line_32 = QtGui.QFrame(self.tab_7)
        self.line_32.setFrameShape(QtGui.QFrame.VLine)
        self.line_32.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_32.setObjectName(_fromUtf8("line_32"))
        self.gridLayout_4.addWidget(self.line_32, 7, 1, 1, 1)
        self.line_31 = QtGui.QFrame(self.tab_7)
        self.line_31.setFrameShape(QtGui.QFrame.VLine)
        self.line_31.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_31.setObjectName(_fromUtf8("line_31"))
        self.gridLayout_4.addWidget(self.line_31, 6, 1, 1, 1)
        self.lineEdit_23 = QtGui.QLineEdit(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_23.setFont(font)
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.gridLayout_4.addWidget(self.lineEdit_23, 2, 2, 1, 1)
        self.label_34 = QtGui.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_4.addWidget(self.label_34, 5, 0, 1, 1)
        self.label_36 = QtGui.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_4.addWidget(self.label_36, 7, 0, 1, 1)
        self.label_32 = QtGui.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_4.addWidget(self.label_32, 3, 0, 1, 1)
        self.line_25 = QtGui.QFrame(self.tab_7)
        self.line_25.setFrameShape(QtGui.QFrame.VLine)
        self.line_25.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_25.setObjectName(_fromUtf8("line_25"))
        self.gridLayout_4.addWidget(self.line_25, 0, 1, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pushButton_8 = QtGui.QPushButton(self.tab_7)
        self.pushButton_8.setIcon(icon)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.horizontalLayout_6.addWidget(self.pushButton_8)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.pushButton_7 = QtGui.QPushButton(self.tab_7)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/update.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon3)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout_6.addWidget(self.pushButton_7)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 8, 2, 1, 1)
        self.tabWidget_3.addTab(self.tab_7, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget_3, 0, 0, 1, 1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/Teachers.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon4, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_2)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_6 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 5, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 1, 0, 1, 1)
        self.fname = QtGui.QLineEdit(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fname.setFont(font)
        self.fname.setObjectName(_fromUtf8("fname"))
        self.gridLayout_5.addWidget(self.fname, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.dateEdit_2 = QtGui.QDateEdit(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit_2.setFont(font)
        self.dateEdit_2.setObjectName(_fromUtf8("dateEdit_2"))
        self.gridLayout_5.addWidget(self.dateEdit_2, 2, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 4, 0, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout_5.addWidget(self.lineEdit_4, 3, 2, 1, 1)
        self.dateEdit = QtGui.QDateEdit(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.gridLayout_5.addWidget(self.dateEdit, 4, 2, 1, 1)
        self.lineEdit_6 = QtGui.QLineEdit(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout_5.addWidget(self.lineEdit_6, 5, 2, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_5.addWidget(self.lineEdit_3, 1, 2, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridLayout_5.addWidget(self.lineEdit_7, 6, 2, 1, 1)
        self.line_2 = QtGui.QFrame(self.tab_3)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_5.addWidget(self.line_2, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 7, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.tab_3)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_5.addWidget(self.line_3, 1, 1, 1, 1)
        self.lineEdit_8 = QtGui.QLineEdit(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout_5.addWidget(self.lineEdit_8, 7, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 6, 0, 1, 1)
        self.line_5 = QtGui.QFrame(self.tab_3)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_5.addWidget(self.line_5, 3, 1, 1, 1)
        self.line_9 = QtGui.QFrame(self.tab_3)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.gridLayout_5.addWidget(self.line_9, 7, 1, 1, 1)
        self.line_6 = QtGui.QFrame(self.tab_3)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_5.addWidget(self.line_6, 4, 1, 1, 1)
        self.line_8 = QtGui.QFrame(self.tab_3)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_5.addWidget(self.line_8, 6, 1, 1, 1)
        self.line_4 = QtGui.QFrame(self.tab_3)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_5.addWidget(self.line_4, 2, 1, 1, 1)
        self.line_7 = QtGui.QFrame(self.tab_3)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_5.addWidget(self.line_7, 5, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_12 = QtGui.QPushButton(self.tab_3)
        self.pushButton_12.setIcon(icon)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.horizontalLayout.addWidget(self.pushButton_12)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.pushButton = QtGui.QPushButton(self.tab_3)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout_5.addLayout(self.horizontalLayout, 8, 2, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_8)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.student = QtGui.QTableWidget(self.tab_8)
        self.student.setObjectName(_fromUtf8("student"))
        self.student.setColumnCount(9)
        self.student.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.student.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.student.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.student.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.student.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.student.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.student.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.student.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.student.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.student.setHorizontalHeaderItem(8, item)
        self.gridLayout_6.addWidget(self.student, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_12 = QtGui.QLabel(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_2.addWidget(self.label_12)
        self.lineEdit_5 = QtGui.QLineEdit(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.horizontalLayout_2.addWidget(self.lineEdit_5)
        self.pushButton_2 = QtGui.QPushButton(self.tab_8)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_8, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.lineEdit_12 = QtGui.QLineEdit(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.gridLayout_7.addWidget(self.lineEdit_12, 0, 2, 1, 1)
        self.line_18 = QtGui.QFrame(self.tab_4)
        self.line_18.setFrameShape(QtGui.QFrame.VLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.gridLayout_7.addWidget(self.line_18, 1, 1, 1, 1)
        self.line_16 = QtGui.QFrame(self.tab_4)
        self.line_16.setFrameShape(QtGui.QFrame.VLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.gridLayout_7.addWidget(self.line_16, 2, 1, 1, 1)
        self.line_17 = QtGui.QFrame(self.tab_4)
        self.line_17.setFrameShape(QtGui.QFrame.VLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.gridLayout_7.addWidget(self.line_17, 0, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_7.addWidget(self.label_14, 1, 0, 1, 1)
        self.dateEdit_4 = QtGui.QDateEdit(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit_4.setFont(font)
        self.dateEdit_4.setObjectName(_fromUtf8("dateEdit_4"))
        self.gridLayout_7.addWidget(self.dateEdit_4, 2, 2, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout_7.addWidget(self.lineEdit_9, 1, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_7.addWidget(self.label_17, 3, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_7.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_7.addWidget(self.label_20, 2, 0, 1, 1)
        self.line_14 = QtGui.QFrame(self.tab_4)
        self.line_14.setFrameShape(QtGui.QFrame.VLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.gridLayout_7.addWidget(self.line_14, 3, 1, 1, 1)
        self.lineEdit_14 = QtGui.QLineEdit(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.gridLayout_7.addWidget(self.lineEdit_14, 3, 2, 1, 1)
        self.line_10 = QtGui.QFrame(self.tab_4)
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.gridLayout_7.addWidget(self.line_10, 4, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_7.addWidget(self.label_16, 6, 0, 1, 1)
        self.line_13 = QtGui.QFrame(self.tab_4)
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.gridLayout_7.addWidget(self.line_13, 7, 1, 1, 1)
        self.line_15 = QtGui.QFrame(self.tab_4)
        self.line_15.setFrameShape(QtGui.QFrame.VLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.gridLayout_7.addWidget(self.line_15, 5, 1, 1, 1)
        self.line_12 = QtGui.QFrame(self.tab_4)
        self.line_12.setFrameShape(QtGui.QFrame.VLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.gridLayout_7.addWidget(self.line_12, 6, 1, 1, 1)
        self.lineEdit_11 = QtGui.QLineEdit(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridLayout_7.addWidget(self.lineEdit_11, 7, 2, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridLayout_7.addWidget(self.lineEdit_10, 5, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_7.addWidget(self.label_15, 7, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_7.addWidget(self.label_18, 4, 0, 1, 1)
        self.dateEdit_3 = QtGui.QDateEdit(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit_3.setFont(font)
        self.dateEdit_3.setObjectName(_fromUtf8("dateEdit_3"))
        self.gridLayout_7.addWidget(self.dateEdit_3, 4, 2, 1, 1)
        self.lineEdit_15 = QtGui.QLineEdit(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.gridLayout_7.addWidget(self.lineEdit_15, 6, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_7.addWidget(self.label_13, 5, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_4 = QtGui.QPushButton(self.tab_4)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.pushButton_3 = QtGui.QPushButton(self.tab_4)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.gridLayout_7.addLayout(self.horizontalLayout_3, 8, 2, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/student-mdl.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon5, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.groupBox = QtGui.QGroupBox(self.tab_9)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 511, 321))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.line_34 = QtGui.QFrame(self.groupBox)
        self.line_34.setGeometry(QtCore.QRect(190, 30, 311, 21))
        self.line_34.setFrameShape(QtGui.QFrame.HLine)
        self.line_34.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_34.setObjectName(_fromUtf8("line_34"))
        self.formLayoutWidget = QtGui.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 80, 351, 181))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_38 = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_38)
        self.lineEdit_27 = QtGui.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_27.setFont(font)
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_27)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtGui.QFormLayout.FieldRole, spacerItem7)
        self.label_39 = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_39)
        self.lineEdit_28 = QtGui.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_28.setFont(font)
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_28)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtGui.QFormLayout.FieldRole, spacerItem8)
        self.label_41 = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_41)
        self.lineEdit_29 = QtGui.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_29.setFont(font)
        self.lineEdit_29.setObjectName(_fromUtf8("lineEdit_29"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_29)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtGui.QFormLayout.FieldRole, spacerItem9)
        self.pushButton_9 = QtGui.QPushButton(self.formLayoutWidget)
        self.pushButton_9.setIcon(icon3)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.pushButton_9)
        self.label_37 = QtGui.QLabel(self.groupBox)
        self.label_37.setGeometry(QtCore.QRect(10, 20, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_9)
        self.groupBox_2.setGeometry(QtCore.QRect(550, 20, 491, 321))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.line_35 = QtGui.QFrame(self.groupBox_2)
        self.line_35.setGeometry(QtCore.QRect(160, 20, 271, 21))
        self.line_35.setFrameShape(QtGui.QFrame.HLine)
        self.line_35.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_35.setObjectName(_fromUtf8("line_35"))
        self.textEdit = QtGui.QTextEdit(self.groupBox_2)
        self.textEdit.setGeometry(QtCore.QRect(40, 60, 411, 191))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.label_40 = QtGui.QLabel(self.groupBox_2)
        self.label_40.setGeometry(QtCore.QRect(40, 10, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/Material Icons_e8b8(0)_32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_9, icon6, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.pushButton_10 = QtGui.QPushButton(Form)
        self.pushButton_10.setBaseSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_10.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon7)
        self.pushButton_10.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.horizontalLayout_7.addWidget(self.pushButton_10)
        self.verticalLayout.addLayout(self.horizontalLayout_7)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QObject.connect(self.pushButton_11, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEdit.clear)
        QtCore.QObject.connect(self.pushButton_11, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEdit_13.clear)
        QtCore.QObject.connect(self.pushButton_11, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEdit_16.clear)
        QtCore.QObject.connect(self.pushButton_11, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEdit_17.clear)
        QtCore.QObject.connect(self.pushButton_11, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEdit_18.clear)
        QtCore.QObject.connect(self.pushButton_11, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEdit_19.clear)
        QtCore.QObject.connect(self.pushButton_12, QtCore.SIGNAL(_fromUtf8("clicked()")), self.fname.clear)
        QtCore.QObject.connect(self.pushButton_12, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEdit_3.clear)
        QtCore.QObject.connect(self.pushButton_12, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEdit_4.clear)
        QtCore.QObject.connect(self.pushButton_12, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEdit_6.clear)
        QtCore.QObject.connect(self.pushButton_12, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEdit_7.clear)
        QtCore.QObject.connect(self.pushButton_12, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEdit_8.clear)
        QtCore.QObject.connect(self.pushButton_10, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_3.setText(_translate("Form", "St. Thomas\' Collage Matale", None))
        self.label_2.setText(_translate("Form", "First Name", None))
        self.label_19.setText(_translate("Form", "Full Name", None))
        self.label_25.setText(_translate("Form", "Address", None))
        self.label_26.setText(_translate("Form", "Contacts", None))
        self.label_23.setText(_translate("Form", "Date Of Birth", None))
        self.label_22.setText(_translate("Form", "NIC No", None))
        self.label_24.setText(_translate("Form", "Admited date of School", None))
        self.pushButton_11.setText(_translate("Form", "Clear", None))
        self.pushButton_5.setText(_translate("Form", "Save", None))
        self.label_27.setText(_translate("Form", "E-Mail", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), _translate("Form", "Add New", None))
        item = self.teacher.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Full Name", None))
        item = self.teacher.horizontalHeaderItem(1)
        item.setText(_translate("Form", "NIC No", None))
        item = self.teacher.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Date Of Birth", None))
        item = self.teacher.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Admited date", None))
        item = self.teacher.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Address", None))
        item = self.teacher.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Contacts", None))
        item = self.teacher.horizontalHeaderItem(6)
        item.setText(_translate("Form", "E-Mail", None))
        self.label_28.setText(_translate("Form", "Enter First Name or NIC No", None))
        self.pushButton_6.setText(_translate("Form", "Search", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("Form", "Search", None))
        self.label_31.setText(_translate("Form", "NIC No", None))
        self.label_33.setText(_translate("Form", "Admited date of school", None))
        self.label_30.setText(_translate("Form", "Full Name", None))
        self.label_35.setText(_translate("Form", "Contacts", None))
        self.label_29.setText(_translate("Form", "First Name", None))
        self.label_34.setText(_translate("Form", "Address", None))
        self.label_36.setText(_translate("Form", "E-Mail", None))
        self.label_32.setText(_translate("Form", "Date Of Birth", None))
        self.pushButton_8.setText(_translate("Form", "Delete", None))
        self.pushButton_7.setText(_translate("Form", "Update", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("Form", "Update/Delete", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Teachers Details", None))
        self.label_6.setText(_translate("Form", "Date Of Birth", None))
        self.label_9.setText(_translate("Form", "Address", None))
        self.label_5.setText(_translate("Form", "NIC No", None))
        self.label_4.setText(_translate("Form", "Full Name", None))
        self.label_7.setText(_translate("Form", "Admission No", None))
        self.label_8.setText(_translate("Form", "Admited Date", None))
        self.label_11.setText(_translate("Form", "Parents Names", None))
        self.label_10.setText(_translate("Form", "Contacts", None))
        self.pushButton_12.setText(_translate("Form", "Clear", None))
        self.pushButton.setText(_translate("Form", "Save", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("Form", "Add New", None))
        item = self.student.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Full Name", None))
        item = self.student.horizontalHeaderItem(1)
        item.setText(_translate("Form", "NIC No", None))
        item = self.student.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Date Of Birth", None))
        item = self.student.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Admission No", None))
        item = self.student.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Admission Date", None))
        item = self.student.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Age", None))
        item = self.student.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Address", None))
        item = self.student.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Contacts", None))
        item = self.student.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Parents Names", None))
        self.label_12.setText(_translate("Form", "Enter Admission No or NIC No", None))
        self.pushButton_2.setText(_translate("Form", "Search", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("Form", "Search", None))
        self.label_14.setText(_translate("Form", "NIC No", None))
        self.label_17.setText(_translate("Form", "Admission No", None))
        self.label_21.setText(_translate("Form", "Full Name", None))
        self.label_20.setText(_translate("Form", "Date Of Birth", None))
        self.label_16.setText(_translate("Form", "Contacts", None))
        self.label_15.setText(_translate("Form", "Parents Names", None))
        self.label_18.setText(_translate("Form", "Admited Date", None))
        self.label_13.setText(_translate("Form", "Address", None))
        self.pushButton_4.setText(_translate("Form", "Delete", None))
        self.pushButton_3.setText(_translate("Form", "Update", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Form", "Update/Delete", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Students Details", None))
        self.label_38.setText(_translate("Form", "Current Password", None))
        self.label_39.setText(_translate("Form", "New Password", None))
        self.label_41.setText(_translate("Form", "Confirm Password", None))
        self.pushButton_9.setText(_translate("Form", "Update password", None))
        self.label_37.setText(_translate("Form", "Change Password ", None))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Developed by Dinushka Piyumal</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">St. Thomas\' Collage Matale</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">13 T1</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">2018 A/L in Technology Stream</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">dinushkapiyumal678@gmail.com</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p></body></html>", None))
        self.label_40.setText(_translate("Form", "About Me :) ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("Form", "Settings", None))
        self.pushButton_10.setText(_translate("Form", "Close", None))

        self.pushButton_5.clicked.connect(self.savet)
        self.pushButton.clicked.connect(self.savest)


import addt_rc
import asss_rc
import clear_st_rc
import clear_t_rc
import close_rc
import delete_s_rc
import delete_t_rc
import flag_rc
import save_s_rc
import save_t_rc
import searctst_rc
import searc_t_rc
import settings_rc
import update_password_rc
import update_s_rc
import update_t_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

